# Generated by Django 2.2.5 on 2019-09-11 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreamy', '0002_auto_20190908_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.AlterUniqueTogether(
            name='userfollower',
            unique_together={('user', 'follower')},
        ),
    ]
