# Generated by Django 2.2.5 on 2019-09-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamy', '0004_auto_20190911_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/static/dreamy/images/default_avatar.png', upload_to='images/'),
        ),
    ]
