# Generated by Django 2.2.5 on 2019-09-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamy', '0006_auto_20190911_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
