# Generated by Django 2.2.5 on 2019-09-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamy', '0007_auto_20190911_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default_avatar.png', upload_to='avatars/'),
            preserve_default=False,
        ),
    ]
